---
- name: "Install PostgreSQL packages"
  become: true
  ansible.builtin.package:
    name:
      - postgresql-server
      - postgresql
      - postgresql-jdbc
      - python3-psycopg2
    state: present
  tags:
    - postgresql
    - candlepin

- name: "Initialize PostgreSQL database"
  become: true
  become_user: postgres
  ansible.builtin.command:
    cmd: pg_ctl initdb -D /var/lib/pgsql/data
    creates: "/var/lib/pgsql/data/PG_VERSION"
  tags:
    - postgresql
    - candlepin

- name: "Configure PostgreSQL to trust local connections (1 of 3)"
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: /var/lib/pgsql/data/pg_hba.conf
    contype: local
    databases: all
    users: all
    method: trust
    create: true
    state: present
  tags:
    - postgresql
    - candlepin

- name: "Configure PostgreSQL to trust local connections (2 of 3)"
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: /var/lib/pgsql/data/pg_hba.conf
    contype: host
    databases: all
    users: all
    address: ::1/128
    method: trust
    create: true
    state: present
  tags:
    - postgresql
    - candlepin

- name: "Configure PostgreSQL to trust local connections (3 of 3)"
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: /var/lib/pgsql/data/pg_hba.conf
    contype: host
    databases: all
    users: all
    address: 127.0.0.1/32
    method: trust
    create: true
    state: present
  tags:
    - postgresql
    - candlepin

- name: "Enable and start the PostgreSQL service"
  become: true
  ansible.builtin.service:
    name: postgresql.service
    enabled: true
    state: started
  tags:
    - postgresql
    - candlepin

- name: "Create the 'candlepin' PostgreSQL user"
  community.postgresql.postgresql_user:
    name: candlepin
    password: candlepin
    role_attr_flags: CREATEDB
  tags:
    - postgresql
    - candlepin

- name: "Create the 'candlepin' PostgreSQL database"
  community.postgresql.postgresql_db:
    name: candlepin
    owner: candlepin
  tags:
    - postgresql
    - candlepin
