version: '3.3'
services:
  db:
    # upgrade to 9.6 requires client version 9.4.1211
    # https://stackoverflow.com/questions/38427585/postgresql-error-column-am-amcanorder-doesnt-exist
    image: ${REGISTRY}/postgres:12
    restart: always
    environment:
      POSTGRES_USER: candlepin
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: candlepin
      POSTGRES_HOST_AUTH_METHOD: trust
  candlepin:
    image: ${REGISTRY}/candlepin-base
    environment:
      USING_POSTGRES: "true"
      DBHOSTNAME: db
      #DBPASSWORD: candlepin
    ports:
      - "8443:8443"
      - "8080:8080"
      - "22:22"
    privileged: true
    volumes:
      - ../:/candlepin-dev
    depends_on:
      - db

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
