## this is just for building the containers, meant to be used with the build-images script
---
version: '3'
services:
  candlepin-base:
    build:
      dockerfile: ./candlepin-base/Dockerfile
      context: .
    image: ${REGISTRY}/candlepin-base
  candlepin-base-cs8:
    build:
      dockerfile: ./candlepin-base-cs8/Dockerfile
      context: .
    image: ${REGISTRY}/candlepin-base-cs8
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
